-- FACT_ORDERS
CREATE OR REPLACE VIEW ECOMMERCE_DB.GOLD.FACT_ORDERS
AS
SELECT
    o.ORDER_ID AS ORDER_ID,
    o.CUSTOMER_ID AS CUSTOMER_ID,
    o.ORDER_STATUS AS ORDER_STATUS,
    o.ORDER_PURCHASE_TIMESTAMP::DATE AS ORDER_DATE,
    o.ORDER_PURCHASE_TIMESTAMP AS ORDER_PURCHASE_TIMESTAMP,
    COUNT(oi.ORDER_ITEM_ID) AS TOTAL_ITEMS,
    ROUND(SUM(oi.PRICE), 2) AS TOTAL_ORDER_VALUE,
    ROUND(SUM(oi.FREIGHT_VALUE), 2) AS TOTAL_FREIGHT_VALUE,
    ROUND(SUM(oi.PRICE) + SUM(oi.FREIGHT_VALUE), 2) AS TOTAL_REVENUE,
    ROUND(SUM(op.PAYMENT_VALUE), 2) AS TOTAL_PAYMENT_VALUE,
    LISTAGG(DISTINCT op.PAYMENT_TYPE, ', ') WITHIN GROUP (ORDER BY op.PAYMENT_TYPE) AS PAYMENT_TYPES
FROM ECOMMERCE_DB.SILVER.ORDERS o
  LEFT JOIN ECOMMERCE_DB.SILVER.ORDER_ITEMS oi
    ON o.ORDER_ID = oi.ORDER_ID
  LEFT JOIN ECOMMERCE_DB.SILVER.ORDER_PAYMENTS op
    ON o.ORDER_ID = op.ORDER_ID
GROUP BY
    o.ORDER_ID,
    o.CUSTOMER_ID,
    o.ORDER_STATUS,
    o.ORDER_PURCHASE_TIMESTAMP;

COMMENT ON VIEW ECOMMERCE_DB.GOLD.FACT_ORDERS IS 'Order-level fact table with revenue, delivery, and review metrics';

-- FACT_ORDER_ITEMS
CREATE OR REPLACE VIEW ECOMMERCE_DB.GOLD.FACT_ORDER_ITEMS
AS
SELECT
    oi.ORDER_ID AS ORDER_ID,
    oi.ORDER_ITEM_ID AS ORDER_ITEM_ID,
    oi.PRODUCT_ID AS PRODUCT_ID,
    oi.SELLER_ID AS SELLER_ID,
    oi.PRICE AS PRICE,
    oi.FREIGHT_VALUE AS FREIGHT_VALUE,
    oi.PRICE + oi.FREIGHT_VALUE AS TOTAL_ITEM_VALUE,
    o.CUSTOMER_ID AS CUSTOMER_ID,
    o.ORDER_STATUS AS ORDER_STATUS,
    o.ORDER_PURCHASE_TIMESTAMP::DATE AS ORDER_DATE,
    p.PRODUCT_CATEGORY_NAME_ENGLISH AS PRODUCT_CATEGORY
FROM ECOMMERCE_DB.SILVER.ORDER_ITEMS oi
  INNER JOIN ECOMMERCE_DB.SILVER.ORDERS o
    ON oi.ORDER_ID = o.ORDER_ID
  LEFT JOIN ECOMMERCE_DB.SILVER.PRODUCTS p
    ON oi.PRODUCT_ID = p.PRODUCT_ID;

COMMENT ON VIEW ECOMMERCE_DB.GOLD.FACT_ORDER_ITEMS IS 'Item-level fact table with product category and seller info';

-- DIM_CUSTOMERS
CREATE OR REPLACE VIEW ECOMMERCE_DB.GOLD.DIM_CUSTOMERS
AS
SELECT c.CUSTOMER_UNIQUE_ID, c.CUSTOMER_ID, c.CUSTOMER_ZIP_CODE_PREFIX, c.CUSTOMER_CITY, c.CUSTOMER_STATE, g.GEOLOCATION_LAT AS CUSTOMER_LAT, g.GEOLOCATION_LNG AS CUSTOMER_LNG FROM ECOMMERCE_DB.SILVER.CUSTOMERS c LEFT JOIN ECOMMERCE_DB.SILVER.GEOLOCATION g ON c.CUSTOMER_ZIP_CODE_PREFIX = g.GEOLOCATION_ZIP_CODE_PREFIX;

USE ROLE ACCOUNTADMIN;

SELECT *
FROM TABLE(INFORMATION_SCHEMA.CORTEX_FUNCTIONS_USAGE_HISTORY(
    date_range_start => DATEADD('day', -7, CURRENT_DATE()),
    date_range_end => CURRENT_DATE()
));

